### ISSUE TITLE
Vestigo fails to resolve route and crashes

### ISSUE THREAD

**Issue by antoooon** [husobee/vestigo#79] opened 2018-02-26 10:38 UTC
First, thanks for a really good router package!

I've run into an issue where vestigo sometimes fails to resolve routes if a shorter route with same prefix is also registered. The issue seems to depend on the order of registering the routes.

Example:
```
package main

import (
	"github.com/husobee/vestigo"
	"net/http"
	"fmt"
)

func main() {
	router := vestigo.NewRouter()

	router.Get("/path/:param1/:param2", func(w http.ResponseWriter, r *http.Request) {
		p1 := vestigo.Param(r, "param1")
		p2 := vestigo.Param(r, "param2")
		w.Write([]byte(fmt.Sprintf("/path/p1/p2, p1='%s', p2='%s'", p1, p2)))
	})

	router.Get("/path/:param1", func(w http.ResponseWriter, r *http.Request) {
		p1 := vestigo.Param(r, "param1")
		w.Write([]byte(fmt.Sprintf("/path/p1, p1='%s'", p1)))
	})

	http.ListenAndServe(":1234", router)
}
```
Build and start the server, then access it:

```
$ curl ":1234/path/p1"
/path/p1, p1='p1'

$ curl ":1234/path/p1/p2"
curl: (52) Empty reply from server
```

Program output:
```
2018/02/26 11:28:07 http: panic serving [fe80::...%Ethernet Connection]:50681: runtime error: index out of range
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc042036400)
        C:/System/Go/src/net/http/server.go:1491 +0x131
panic(0x618240, 0xc042004060)
        C:/System/Go/src/runtime/panic.go:458 +0x251
github.com/husobee/vestigo.(*Router).find(0xc042004eb0, 0xc0420b02d0, 0x65b630, 0x65b684, 0x6)
        C:/Work/go/src/github.com/husobee/vestigo/router.go:227 +0x11ae
github.com/husobee/vestigo.(*Router).Find(0xc042004eb0, 0xc0420b02d0, 0x65b630)
        C:/Work/go/src/github.com/husobee/vestigo/router.go:171 +0x3c
github.com/husobee/vestigo.(*Router).ServeHTTP(0xc042004eb0, 0x7502c0, 0xc042039c70, 0xc0420b02d0)
        C:/Work/go/src/github.com/husobee/vestigo/router.go:66 +0x3c
net/http.serverHandler.ServeHTTP(0xc042036200, 0x7502c0, 0xc042039c70, 0xc0420b02d0)
        C:/System/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042036400, 0x750680, 0xc042008a00)
        C:/System/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/System/Go/src/net/http/server.go:2293 +0x454
```

If I change the order of adding the routes, it works. This is however very error prone in my main application since it registers a lot of routes, and accidentally breaking the server becomes easy.

**Comment by husobee** [comment] 2018-02-26 13:24
I was able to reproduce in a unit test.  Will work through the issue.

**Comment by husobee** [comment] 2018-02-26 18:49
@antoooon: I believe I have found the root of the problem.  It has to do with assigning lists of parameter values to new nodes from old nodes when the insertions are happening.  The way we are doing it currently causes the bug as we are actually assigning the reference to the list as opposed to creating a new list, so when you add a new route that has to break an old route branch, since we are copying the reference, when it is updated, the old node is being updated as well.  Will fix this tonight and push a fix out.  Thanks for catching this issue.

**Comment by husobee** [comment] 2018-02-27 13:37
@antoooon: I believe I was able to resolve this.  Currently sitting in branch issue79.  Would you be able to confirm this will work for you?  I will merge then.

**Comment by noahbjohnson** [comment] 2020-10-08 15:11
Changes on branch issue79 are fixing this issue for me. Will you be able to get this merged?

**Closed** 2020-10-08 16:06 UTC
